// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __bio__dataExt_hh__
#define __bio__dataExt_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_bio__dataExt
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_bio__dataExt
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_bio__dataExt
#endif



#ifndef __DataType_hh_EXTERNAL_GUARD__
#define __DataType_hh_EXTERNAL_GUARD__
#include <ossie/CF/DataType.h>
#endif
#ifndef __Port_hh_EXTERNAL_GUARD__
#define __Port_hh_EXTERNAL_GUARD__
#include <ossie/CF/Port.h>
#endif
#ifndef __QueryablePort_hh_EXTERNAL_GUARD__
#define __QueryablePort_hh_EXTERNAL_GUARD__
#include <ossie/CF/QueryablePort.h>
#endif
#ifndef __NegotiablePort_hh_EXTERNAL_GUARD__
#define __NegotiablePort_hh_EXTERNAL_GUARD__
#include <ossie/CF/NegotiablePort.h>
#endif
#ifndef __PortTypes_hh_EXTERNAL_GUARD__
#define __PortTypes_hh_EXTERNAL_GUARD__
#include <ossie/CF/PortTypes.h>
#endif
#ifndef __bulkioDataTypes_hh_EXTERNAL_GUARD__
#define __bulkioDataTypes_hh_EXTERNAL_GUARD__
#include <ossie/BULKIO/bulkioDataTypes.h>
#endif
#ifndef __bio__runtimeStats_hh_EXTERNAL_GUARD__
#define __bio__runtimeStats_hh_EXTERNAL_GUARD__
#include <ossie/BULKIO/bio_runtimeStats.h>
#endif
#ifndef __bio__updateSRI_hh_EXTERNAL_GUARD__
#define __bio__updateSRI_hh_EXTERNAL_GUARD__
#include <ossie/BULKIO/bio_updateSRI.h>
#endif
#ifndef __bio__dataChar_hh_EXTERNAL_GUARD__
#define __bio__dataChar_hh_EXTERNAL_GUARD__
#include <ossie/BULKIO/bio_dataChar.h>
#endif
#ifndef __bio__dataDouble_hh_EXTERNAL_GUARD__
#define __bio__dataDouble_hh_EXTERNAL_GUARD__
#include <ossie/BULKIO/bio_dataDouble.h>
#endif
#ifndef __bio__dataFloat_hh_EXTERNAL_GUARD__
#define __bio__dataFloat_hh_EXTERNAL_GUARD__
#include <ossie/BULKIO/bio_dataFloat.h>
#endif
#ifndef __bio__dataLong_hh_EXTERNAL_GUARD__
#define __bio__dataLong_hh_EXTERNAL_GUARD__
#include <ossie/BULKIO/bio_dataLong.h>
#endif
#ifndef __bio__dataLongLong_hh_EXTERNAL_GUARD__
#define __bio__dataLongLong_hh_EXTERNAL_GUARD__
#include <ossie/BULKIO/bio_dataLongLong.h>
#endif
#ifndef __bio__dataOctet_hh_EXTERNAL_GUARD__
#define __bio__dataOctet_hh_EXTERNAL_GUARD__
#include <ossie/BULKIO/bio_dataOctet.h>
#endif
#ifndef __bio__dataShort_hh_EXTERNAL_GUARD__
#define __bio__dataShort_hh_EXTERNAL_GUARD__
#include <ossie/BULKIO/bio_dataShort.h>
#endif
#ifndef __bio__dataUlong_hh_EXTERNAL_GUARD__
#define __bio__dataUlong_hh_EXTERNAL_GUARD__
#include <ossie/BULKIO/bio_dataUlong.h>
#endif
#ifndef __bio__dataUlongLong_hh_EXTERNAL_GUARD__
#define __bio__dataUlongLong_hh_EXTERNAL_GUARD__
#include <ossie/BULKIO/bio_dataUlongLong.h>
#endif
#ifndef __bio__dataUshort_hh_EXTERNAL_GUARD__
#define __bio__dataUshort_hh_EXTERNAL_GUARD__
#include <ossie/BULKIO/bio_dataUshort.h>
#endif
#ifndef __bio__dataBit_hh_EXTERNAL_GUARD__
#define __bio__dataBit_hh_EXTERNAL_GUARD__
#include <ossie/BULKIO/bio_dataBit.h>
#endif
#ifndef __bio__dataXML_hh_EXTERNAL_GUARD__
#define __bio__dataXML_hh_EXTERNAL_GUARD__
#include <ossie/BULKIO/bio_dataXML.h>
#endif
#ifndef __bio__dataFile_hh_EXTERNAL_GUARD__
#define __bio__dataFile_hh_EXTERNAL_GUARD__
#include <ossie/BULKIO/bio_dataFile.h>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE BULKIO

_CORBA_MODULE_BEG

  _CORBA_MODULE internal

  _CORBA_MODULE_BEG

#ifndef __BULKIO_minternal_mUsesPortStatisticsProviderExt__
#define __BULKIO_minternal_mUsesPortStatisticsProviderExt__
    class UsesPortStatisticsProviderExt;
    class _objref_UsesPortStatisticsProviderExt;
    class _impl_UsesPortStatisticsProviderExt;
    
    typedef _objref_UsesPortStatisticsProviderExt* UsesPortStatisticsProviderExt_ptr;
    typedef UsesPortStatisticsProviderExt_ptr UsesPortStatisticsProviderExtRef;

    class UsesPortStatisticsProviderExt_Helper {
    public:
      typedef UsesPortStatisticsProviderExt_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_UsesPortStatisticsProviderExt, UsesPortStatisticsProviderExt_Helper> UsesPortStatisticsProviderExt_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_UsesPortStatisticsProviderExt,UsesPortStatisticsProviderExt_Helper > UsesPortStatisticsProviderExt_out;

#endif

    // interface UsesPortStatisticsProviderExt
    class UsesPortStatisticsProviderExt {
    public:
      // Declarations for this interface type.
      typedef UsesPortStatisticsProviderExt_ptr _ptr_type;
      typedef UsesPortStatisticsProviderExt_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static inline _ptr_type _fromObjRef(omniObjRef* o) {
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_UsesPortStatisticsProviderExt :
      public virtual _objref_UsesPortStatisticsProvider,
      public virtual ExtendedCF::_objref_NegotiableUsesPort
    {
    public:
      // IDL operations
      

      // Constructors
      inline _objref_UsesPortStatisticsProviderExt()  { _PR_setobj(0); }  // nil
      _objref_UsesPortStatisticsProviderExt(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_UsesPortStatisticsProviderExt();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_UsesPortStatisticsProviderExt(const _objref_UsesPortStatisticsProviderExt&);
      _objref_UsesPortStatisticsProviderExt& operator = (const _objref_UsesPortStatisticsProviderExt&);
      // not implemented

      friend class UsesPortStatisticsProviderExt;
    };

    class _pof_UsesPortStatisticsProviderExt : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_UsesPortStatisticsProviderExt() : _OMNI_NS(proxyObjectFactory)(UsesPortStatisticsProviderExt::_PD_repoId) {}
      virtual ~_pof_UsesPortStatisticsProviderExt();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_UsesPortStatisticsProviderExt :
      public virtual _impl_UsesPortStatisticsProvider,
      public virtual ExtendedCF::_impl_NegotiableUsesPort
    {
    public:
      virtual ~_impl_UsesPortStatisticsProviderExt();

      
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


    _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_UsesPortStatisticsProviderExt;

#ifndef __BULKIO_minternal_mdataCharExt__
#define __BULKIO_minternal_mdataCharExt__
    class dataCharExt;
    class _objref_dataCharExt;
    class _impl_dataCharExt;
    
    typedef _objref_dataCharExt* dataCharExt_ptr;
    typedef dataCharExt_ptr dataCharExtRef;

    class dataCharExt_Helper {
    public:
      typedef dataCharExt_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_dataCharExt, dataCharExt_Helper> dataCharExt_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_dataCharExt,dataCharExt_Helper > dataCharExt_out;

#endif

    // interface dataCharExt
    class dataCharExt {
    public:
      // Declarations for this interface type.
      typedef dataCharExt_ptr _ptr_type;
      typedef dataCharExt_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static inline _ptr_type _fromObjRef(omniObjRef* o) {
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_dataCharExt :
      public virtual _objref_dataChar,
      public virtual ExtendedCF::_objref_NegotiableProvidesPort
    {
    public:
      // IDL operations
      

      // Constructors
      inline _objref_dataCharExt()  { _PR_setobj(0); }  // nil
      _objref_dataCharExt(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_dataCharExt();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_dataCharExt(const _objref_dataCharExt&);
      _objref_dataCharExt& operator = (const _objref_dataCharExt&);
      // not implemented

      friend class dataCharExt;
    };

    class _pof_dataCharExt : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_dataCharExt() : _OMNI_NS(proxyObjectFactory)(dataCharExt::_PD_repoId) {}
      virtual ~_pof_dataCharExt();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_dataCharExt :
      public virtual _impl_dataChar,
      public virtual ExtendedCF::_impl_NegotiableProvidesPort
    {
    public:
      virtual ~_impl_dataCharExt();

      
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


    _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_dataCharExt;

#ifndef __BULKIO_minternal_mdataDoubleExt__
#define __BULKIO_minternal_mdataDoubleExt__
    class dataDoubleExt;
    class _objref_dataDoubleExt;
    class _impl_dataDoubleExt;
    
    typedef _objref_dataDoubleExt* dataDoubleExt_ptr;
    typedef dataDoubleExt_ptr dataDoubleExtRef;

    class dataDoubleExt_Helper {
    public:
      typedef dataDoubleExt_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_dataDoubleExt, dataDoubleExt_Helper> dataDoubleExt_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_dataDoubleExt,dataDoubleExt_Helper > dataDoubleExt_out;

#endif

    // interface dataDoubleExt
    class dataDoubleExt {
    public:
      // Declarations for this interface type.
      typedef dataDoubleExt_ptr _ptr_type;
      typedef dataDoubleExt_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static inline _ptr_type _fromObjRef(omniObjRef* o) {
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_dataDoubleExt :
      public virtual _objref_dataDouble,
      public virtual ExtendedCF::_objref_NegotiableProvidesPort
    {
    public:
      // IDL operations
      

      // Constructors
      inline _objref_dataDoubleExt()  { _PR_setobj(0); }  // nil
      _objref_dataDoubleExt(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_dataDoubleExt();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_dataDoubleExt(const _objref_dataDoubleExt&);
      _objref_dataDoubleExt& operator = (const _objref_dataDoubleExt&);
      // not implemented

      friend class dataDoubleExt;
    };

    class _pof_dataDoubleExt : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_dataDoubleExt() : _OMNI_NS(proxyObjectFactory)(dataDoubleExt::_PD_repoId) {}
      virtual ~_pof_dataDoubleExt();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_dataDoubleExt :
      public virtual _impl_dataDouble,
      public virtual ExtendedCF::_impl_NegotiableProvidesPort
    {
    public:
      virtual ~_impl_dataDoubleExt();

      
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


    _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_dataDoubleExt;

#ifndef __BULKIO_minternal_mdataFloatExt__
#define __BULKIO_minternal_mdataFloatExt__
    class dataFloatExt;
    class _objref_dataFloatExt;
    class _impl_dataFloatExt;
    
    typedef _objref_dataFloatExt* dataFloatExt_ptr;
    typedef dataFloatExt_ptr dataFloatExtRef;

    class dataFloatExt_Helper {
    public:
      typedef dataFloatExt_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_dataFloatExt, dataFloatExt_Helper> dataFloatExt_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_dataFloatExt,dataFloatExt_Helper > dataFloatExt_out;

#endif

    // interface dataFloatExt
    class dataFloatExt {
    public:
      // Declarations for this interface type.
      typedef dataFloatExt_ptr _ptr_type;
      typedef dataFloatExt_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static inline _ptr_type _fromObjRef(omniObjRef* o) {
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_dataFloatExt :
      public virtual _objref_dataFloat,
      public virtual ExtendedCF::_objref_NegotiableProvidesPort
    {
    public:
      // IDL operations
      

      // Constructors
      inline _objref_dataFloatExt()  { _PR_setobj(0); }  // nil
      _objref_dataFloatExt(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_dataFloatExt();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_dataFloatExt(const _objref_dataFloatExt&);
      _objref_dataFloatExt& operator = (const _objref_dataFloatExt&);
      // not implemented

      friend class dataFloatExt;
    };

    class _pof_dataFloatExt : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_dataFloatExt() : _OMNI_NS(proxyObjectFactory)(dataFloatExt::_PD_repoId) {}
      virtual ~_pof_dataFloatExt();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_dataFloatExt :
      public virtual _impl_dataFloat,
      public virtual ExtendedCF::_impl_NegotiableProvidesPort
    {
    public:
      virtual ~_impl_dataFloatExt();

      
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


    _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_dataFloatExt;

#ifndef __BULKIO_minternal_mdataLongExt__
#define __BULKIO_minternal_mdataLongExt__
    class dataLongExt;
    class _objref_dataLongExt;
    class _impl_dataLongExt;
    
    typedef _objref_dataLongExt* dataLongExt_ptr;
    typedef dataLongExt_ptr dataLongExtRef;

    class dataLongExt_Helper {
    public:
      typedef dataLongExt_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_dataLongExt, dataLongExt_Helper> dataLongExt_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_dataLongExt,dataLongExt_Helper > dataLongExt_out;

#endif

    // interface dataLongExt
    class dataLongExt {
    public:
      // Declarations for this interface type.
      typedef dataLongExt_ptr _ptr_type;
      typedef dataLongExt_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static inline _ptr_type _fromObjRef(omniObjRef* o) {
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_dataLongExt :
      public virtual _objref_dataLong,
      public virtual ExtendedCF::_objref_NegotiableProvidesPort
    {
    public:
      // IDL operations
      

      // Constructors
      inline _objref_dataLongExt()  { _PR_setobj(0); }  // nil
      _objref_dataLongExt(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_dataLongExt();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_dataLongExt(const _objref_dataLongExt&);
      _objref_dataLongExt& operator = (const _objref_dataLongExt&);
      // not implemented

      friend class dataLongExt;
    };

    class _pof_dataLongExt : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_dataLongExt() : _OMNI_NS(proxyObjectFactory)(dataLongExt::_PD_repoId) {}
      virtual ~_pof_dataLongExt();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_dataLongExt :
      public virtual _impl_dataLong,
      public virtual ExtendedCF::_impl_NegotiableProvidesPort
    {
    public:
      virtual ~_impl_dataLongExt();

      
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


    _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_dataLongExt;

#ifndef __BULKIO_minternal_mdataLongLongExt__
#define __BULKIO_minternal_mdataLongLongExt__
    class dataLongLongExt;
    class _objref_dataLongLongExt;
    class _impl_dataLongLongExt;
    
    typedef _objref_dataLongLongExt* dataLongLongExt_ptr;
    typedef dataLongLongExt_ptr dataLongLongExtRef;

    class dataLongLongExt_Helper {
    public:
      typedef dataLongLongExt_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_dataLongLongExt, dataLongLongExt_Helper> dataLongLongExt_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_dataLongLongExt,dataLongLongExt_Helper > dataLongLongExt_out;

#endif

    // interface dataLongLongExt
    class dataLongLongExt {
    public:
      // Declarations for this interface type.
      typedef dataLongLongExt_ptr _ptr_type;
      typedef dataLongLongExt_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static inline _ptr_type _fromObjRef(omniObjRef* o) {
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_dataLongLongExt :
      public virtual _objref_dataLongLong,
      public virtual ExtendedCF::_objref_NegotiableProvidesPort
    {
    public:
      // IDL operations
      

      // Constructors
      inline _objref_dataLongLongExt()  { _PR_setobj(0); }  // nil
      _objref_dataLongLongExt(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_dataLongLongExt();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_dataLongLongExt(const _objref_dataLongLongExt&);
      _objref_dataLongLongExt& operator = (const _objref_dataLongLongExt&);
      // not implemented

      friend class dataLongLongExt;
    };

    class _pof_dataLongLongExt : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_dataLongLongExt() : _OMNI_NS(proxyObjectFactory)(dataLongLongExt::_PD_repoId) {}
      virtual ~_pof_dataLongLongExt();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_dataLongLongExt :
      public virtual _impl_dataLongLong,
      public virtual ExtendedCF::_impl_NegotiableProvidesPort
    {
    public:
      virtual ~_impl_dataLongLongExt();

      
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


    _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_dataLongLongExt;

#ifndef __BULKIO_minternal_mdataOctetExt__
#define __BULKIO_minternal_mdataOctetExt__
    class dataOctetExt;
    class _objref_dataOctetExt;
    class _impl_dataOctetExt;
    
    typedef _objref_dataOctetExt* dataOctetExt_ptr;
    typedef dataOctetExt_ptr dataOctetExtRef;

    class dataOctetExt_Helper {
    public:
      typedef dataOctetExt_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_dataOctetExt, dataOctetExt_Helper> dataOctetExt_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_dataOctetExt,dataOctetExt_Helper > dataOctetExt_out;

#endif

    // interface dataOctetExt
    class dataOctetExt {
    public:
      // Declarations for this interface type.
      typedef dataOctetExt_ptr _ptr_type;
      typedef dataOctetExt_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static inline _ptr_type _fromObjRef(omniObjRef* o) {
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_dataOctetExt :
      public virtual _objref_dataOctet,
      public virtual ExtendedCF::_objref_NegotiableProvidesPort
    {
    public:
      // IDL operations
      

      // Constructors
      inline _objref_dataOctetExt()  { _PR_setobj(0); }  // nil
      _objref_dataOctetExt(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_dataOctetExt();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_dataOctetExt(const _objref_dataOctetExt&);
      _objref_dataOctetExt& operator = (const _objref_dataOctetExt&);
      // not implemented

      friend class dataOctetExt;
    };

    class _pof_dataOctetExt : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_dataOctetExt() : _OMNI_NS(proxyObjectFactory)(dataOctetExt::_PD_repoId) {}
      virtual ~_pof_dataOctetExt();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_dataOctetExt :
      public virtual _impl_dataOctet,
      public virtual ExtendedCF::_impl_NegotiableProvidesPort
    {
    public:
      virtual ~_impl_dataOctetExt();

      
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


    _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_dataOctetExt;

#ifndef __BULKIO_minternal_mdataShortExt__
#define __BULKIO_minternal_mdataShortExt__
    class dataShortExt;
    class _objref_dataShortExt;
    class _impl_dataShortExt;
    
    typedef _objref_dataShortExt* dataShortExt_ptr;
    typedef dataShortExt_ptr dataShortExtRef;

    class dataShortExt_Helper {
    public:
      typedef dataShortExt_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_dataShortExt, dataShortExt_Helper> dataShortExt_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_dataShortExt,dataShortExt_Helper > dataShortExt_out;

#endif

    // interface dataShortExt
    class dataShortExt {
    public:
      // Declarations for this interface type.
      typedef dataShortExt_ptr _ptr_type;
      typedef dataShortExt_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static inline _ptr_type _fromObjRef(omniObjRef* o) {
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_dataShortExt :
      public virtual _objref_dataShort,
      public virtual ExtendedCF::_objref_NegotiableProvidesPort
    {
    public:
      // IDL operations
      

      // Constructors
      inline _objref_dataShortExt()  { _PR_setobj(0); }  // nil
      _objref_dataShortExt(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_dataShortExt();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_dataShortExt(const _objref_dataShortExt&);
      _objref_dataShortExt& operator = (const _objref_dataShortExt&);
      // not implemented

      friend class dataShortExt;
    };

    class _pof_dataShortExt : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_dataShortExt() : _OMNI_NS(proxyObjectFactory)(dataShortExt::_PD_repoId) {}
      virtual ~_pof_dataShortExt();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_dataShortExt :
      public virtual _impl_dataShort,
      public virtual ExtendedCF::_impl_NegotiableProvidesPort
    {
    public:
      virtual ~_impl_dataShortExt();

      
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


    _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_dataShortExt;

#ifndef __BULKIO_minternal_mdataUlongExt__
#define __BULKIO_minternal_mdataUlongExt__
    class dataUlongExt;
    class _objref_dataUlongExt;
    class _impl_dataUlongExt;
    
    typedef _objref_dataUlongExt* dataUlongExt_ptr;
    typedef dataUlongExt_ptr dataUlongExtRef;

    class dataUlongExt_Helper {
    public:
      typedef dataUlongExt_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_dataUlongExt, dataUlongExt_Helper> dataUlongExt_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_dataUlongExt,dataUlongExt_Helper > dataUlongExt_out;

#endif

    // interface dataUlongExt
    class dataUlongExt {
    public:
      // Declarations for this interface type.
      typedef dataUlongExt_ptr _ptr_type;
      typedef dataUlongExt_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static inline _ptr_type _fromObjRef(omniObjRef* o) {
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_dataUlongExt :
      public virtual _objref_dataUlong,
      public virtual ExtendedCF::_objref_NegotiableProvidesPort
    {
    public:
      // IDL operations
      

      // Constructors
      inline _objref_dataUlongExt()  { _PR_setobj(0); }  // nil
      _objref_dataUlongExt(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_dataUlongExt();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_dataUlongExt(const _objref_dataUlongExt&);
      _objref_dataUlongExt& operator = (const _objref_dataUlongExt&);
      // not implemented

      friend class dataUlongExt;
    };

    class _pof_dataUlongExt : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_dataUlongExt() : _OMNI_NS(proxyObjectFactory)(dataUlongExt::_PD_repoId) {}
      virtual ~_pof_dataUlongExt();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_dataUlongExt :
      public virtual _impl_dataUlong,
      public virtual ExtendedCF::_impl_NegotiableProvidesPort
    {
    public:
      virtual ~_impl_dataUlongExt();

      
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


    _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_dataUlongExt;

#ifndef __BULKIO_minternal_mdataUlongLongExt__
#define __BULKIO_minternal_mdataUlongLongExt__
    class dataUlongLongExt;
    class _objref_dataUlongLongExt;
    class _impl_dataUlongLongExt;
    
    typedef _objref_dataUlongLongExt* dataUlongLongExt_ptr;
    typedef dataUlongLongExt_ptr dataUlongLongExtRef;

    class dataUlongLongExt_Helper {
    public:
      typedef dataUlongLongExt_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_dataUlongLongExt, dataUlongLongExt_Helper> dataUlongLongExt_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_dataUlongLongExt,dataUlongLongExt_Helper > dataUlongLongExt_out;

#endif

    // interface dataUlongLongExt
    class dataUlongLongExt {
    public:
      // Declarations for this interface type.
      typedef dataUlongLongExt_ptr _ptr_type;
      typedef dataUlongLongExt_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static inline _ptr_type _fromObjRef(omniObjRef* o) {
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_dataUlongLongExt :
      public virtual _objref_dataUlongLong,
      public virtual ExtendedCF::_objref_NegotiableProvidesPort
    {
    public:
      // IDL operations
      

      // Constructors
      inline _objref_dataUlongLongExt()  { _PR_setobj(0); }  // nil
      _objref_dataUlongLongExt(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_dataUlongLongExt();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_dataUlongLongExt(const _objref_dataUlongLongExt&);
      _objref_dataUlongLongExt& operator = (const _objref_dataUlongLongExt&);
      // not implemented

      friend class dataUlongLongExt;
    };

    class _pof_dataUlongLongExt : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_dataUlongLongExt() : _OMNI_NS(proxyObjectFactory)(dataUlongLongExt::_PD_repoId) {}
      virtual ~_pof_dataUlongLongExt();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_dataUlongLongExt :
      public virtual _impl_dataUlongLong,
      public virtual ExtendedCF::_impl_NegotiableProvidesPort
    {
    public:
      virtual ~_impl_dataUlongLongExt();

      
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


    _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_dataUlongLongExt;

#ifndef __BULKIO_minternal_mdataUshortExt__
#define __BULKIO_minternal_mdataUshortExt__
    class dataUshortExt;
    class _objref_dataUshortExt;
    class _impl_dataUshortExt;
    
    typedef _objref_dataUshortExt* dataUshortExt_ptr;
    typedef dataUshortExt_ptr dataUshortExtRef;

    class dataUshortExt_Helper {
    public:
      typedef dataUshortExt_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_dataUshortExt, dataUshortExt_Helper> dataUshortExt_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_dataUshortExt,dataUshortExt_Helper > dataUshortExt_out;

#endif

    // interface dataUshortExt
    class dataUshortExt {
    public:
      // Declarations for this interface type.
      typedef dataUshortExt_ptr _ptr_type;
      typedef dataUshortExt_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static inline _ptr_type _fromObjRef(omniObjRef* o) {
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_dataUshortExt :
      public virtual _objref_dataUshort,
      public virtual ExtendedCF::_objref_NegotiableProvidesPort
    {
    public:
      // IDL operations
      

      // Constructors
      inline _objref_dataUshortExt()  { _PR_setobj(0); }  // nil
      _objref_dataUshortExt(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_dataUshortExt();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_dataUshortExt(const _objref_dataUshortExt&);
      _objref_dataUshortExt& operator = (const _objref_dataUshortExt&);
      // not implemented

      friend class dataUshortExt;
    };

    class _pof_dataUshortExt : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_dataUshortExt() : _OMNI_NS(proxyObjectFactory)(dataUshortExt::_PD_repoId) {}
      virtual ~_pof_dataUshortExt();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_dataUshortExt :
      public virtual _impl_dataUshort,
      public virtual ExtendedCF::_impl_NegotiableProvidesPort
    {
    public:
      virtual ~_impl_dataUshortExt();

      
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


    _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_dataUshortExt;

#ifndef __BULKIO_minternal_mdataBitExt__
#define __BULKIO_minternal_mdataBitExt__
    class dataBitExt;
    class _objref_dataBitExt;
    class _impl_dataBitExt;
    
    typedef _objref_dataBitExt* dataBitExt_ptr;
    typedef dataBitExt_ptr dataBitExtRef;

    class dataBitExt_Helper {
    public:
      typedef dataBitExt_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_dataBitExt, dataBitExt_Helper> dataBitExt_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_dataBitExt,dataBitExt_Helper > dataBitExt_out;

#endif

    // interface dataBitExt
    class dataBitExt {
    public:
      // Declarations for this interface type.
      typedef dataBitExt_ptr _ptr_type;
      typedef dataBitExt_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static inline _ptr_type _fromObjRef(omniObjRef* o) {
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_dataBitExt :
      public virtual _objref_dataBit,
      public virtual ExtendedCF::_objref_NegotiableProvidesPort
    {
    public:
      // IDL operations
      

      // Constructors
      inline _objref_dataBitExt()  { _PR_setobj(0); }  // nil
      _objref_dataBitExt(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_dataBitExt();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_dataBitExt(const _objref_dataBitExt&);
      _objref_dataBitExt& operator = (const _objref_dataBitExt&);
      // not implemented

      friend class dataBitExt;
    };

    class _pof_dataBitExt : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_dataBitExt() : _OMNI_NS(proxyObjectFactory)(dataBitExt::_PD_repoId) {}
      virtual ~_pof_dataBitExt();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_dataBitExt :
      public virtual _impl_dataBit,
      public virtual ExtendedCF::_impl_NegotiableProvidesPort
    {
    public:
      virtual ~_impl_dataBitExt();

      
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


    _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_dataBitExt;

#ifndef __BULKIO_minternal_mdataXMLExt__
#define __BULKIO_minternal_mdataXMLExt__
    class dataXMLExt;
    class _objref_dataXMLExt;
    class _impl_dataXMLExt;
    
    typedef _objref_dataXMLExt* dataXMLExt_ptr;
    typedef dataXMLExt_ptr dataXMLExtRef;

    class dataXMLExt_Helper {
    public:
      typedef dataXMLExt_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_dataXMLExt, dataXMLExt_Helper> dataXMLExt_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_dataXMLExt,dataXMLExt_Helper > dataXMLExt_out;

#endif

    // interface dataXMLExt
    class dataXMLExt {
    public:
      // Declarations for this interface type.
      typedef dataXMLExt_ptr _ptr_type;
      typedef dataXMLExt_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static inline _ptr_type _fromObjRef(omniObjRef* o) {
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_dataXMLExt :
      public virtual _objref_dataXML,
      public virtual ExtendedCF::_objref_NegotiableProvidesPort
    {
    public:
      // IDL operations
      

      // Constructors
      inline _objref_dataXMLExt()  { _PR_setobj(0); }  // nil
      _objref_dataXMLExt(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_dataXMLExt();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_dataXMLExt(const _objref_dataXMLExt&);
      _objref_dataXMLExt& operator = (const _objref_dataXMLExt&);
      // not implemented

      friend class dataXMLExt;
    };

    class _pof_dataXMLExt : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_dataXMLExt() : _OMNI_NS(proxyObjectFactory)(dataXMLExt::_PD_repoId) {}
      virtual ~_pof_dataXMLExt();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_dataXMLExt :
      public virtual _impl_dataXML,
      public virtual ExtendedCF::_impl_NegotiableProvidesPort
    {
    public:
      virtual ~_impl_dataXMLExt();

      
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


    _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_dataXMLExt;

#ifndef __BULKIO_minternal_mdataFileExt__
#define __BULKIO_minternal_mdataFileExt__
    class dataFileExt;
    class _objref_dataFileExt;
    class _impl_dataFileExt;
    
    typedef _objref_dataFileExt* dataFileExt_ptr;
    typedef dataFileExt_ptr dataFileExtRef;

    class dataFileExt_Helper {
    public:
      typedef dataFileExt_ptr _ptr_type;

      static _ptr_type _nil();
      static _CORBA_Boolean is_nil(_ptr_type);
      static void release(_ptr_type);
      static void duplicate(_ptr_type);
      static void marshalObjRef(_ptr_type, cdrStream&);
      static _ptr_type unmarshalObjRef(cdrStream&);
    };

    typedef _CORBA_ObjRef_Var<_objref_dataFileExt, dataFileExt_Helper> dataFileExt_var;
    typedef _CORBA_ObjRef_OUT_arg<_objref_dataFileExt,dataFileExt_Helper > dataFileExt_out;

#endif

    // interface dataFileExt
    class dataFileExt {
    public:
      // Declarations for this interface type.
      typedef dataFileExt_ptr _ptr_type;
      typedef dataFileExt_var _var_type;

      static _ptr_type _duplicate(_ptr_type);
      static _ptr_type _narrow(::CORBA::Object_ptr);
      static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
      
      static _ptr_type _nil();

      static inline void _marshalObjRef(_ptr_type, cdrStream&);

      static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
        omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static inline _ptr_type _fromObjRef(omniObjRef* o) {
        if (o)
          return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
        else
          return _nil();
      }

      static _core_attr const char* _PD_repoId;

      // Other IDL defined within this scope.
      
    };

    class _objref_dataFileExt :
      public virtual _objref_dataFile,
      public virtual ExtendedCF::_objref_NegotiableProvidesPort
    {
    public:
      // IDL operations
      

      // Constructors
      inline _objref_dataFileExt()  { _PR_setobj(0); }  // nil
      _objref_dataFileExt(omniIOR*, omniIdentity*);

    protected:
      virtual ~_objref_dataFileExt();

      
    private:
      virtual void* _ptrToObjRef(const char*);

      _objref_dataFileExt(const _objref_dataFileExt&);
      _objref_dataFileExt& operator = (const _objref_dataFileExt&);
      // not implemented

      friend class dataFileExt;
    };

    class _pof_dataFileExt : public _OMNI_NS(proxyObjectFactory) {
    public:
      inline _pof_dataFileExt() : _OMNI_NS(proxyObjectFactory)(dataFileExt::_PD_repoId) {}
      virtual ~_pof_dataFileExt();

      virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
      virtual _CORBA_Boolean is_a(const char*) const;
    };

    class _impl_dataFileExt :
      public virtual _impl_dataFile,
      public virtual ExtendedCF::_impl_NegotiableProvidesPort
    {
    public:
      virtual ~_impl_dataFileExt();

      
      
    public:  // Really protected, workaround for xlC
      virtual _CORBA_Boolean _dispatch(omniCallHandle&);

    private:
      virtual void* _ptrToInterface(const char*);
      virtual const char* _mostDerivedRepoId();
      
    };


    _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_dataFileExt;

  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE POA_BULKIO
_CORBA_MODULE_BEG

  _CORBA_MODULE internal
  _CORBA_MODULE_BEG

    class UsesPortStatisticsProviderExt :
      public virtual BULKIO::internal::_impl_UsesPortStatisticsProviderExt,
      public virtual UsesPortStatisticsProvider,
        public virtual POA_ExtendedCF::NegotiableUsesPort
    {
    public:
      virtual ~UsesPortStatisticsProviderExt();

      inline ::BULKIO::internal::UsesPortStatisticsProviderExt_ptr _this() {
        return (::BULKIO::internal::UsesPortStatisticsProviderExt_ptr) _do_this(::BULKIO::internal::UsesPortStatisticsProviderExt::_PD_repoId);
      }
    };

    class dataCharExt :
      public virtual BULKIO::internal::_impl_dataCharExt,
      public virtual dataChar,
        public virtual POA_ExtendedCF::NegotiableProvidesPort
    {
    public:
      virtual ~dataCharExt();

      inline ::BULKIO::internal::dataCharExt_ptr _this() {
        return (::BULKIO::internal::dataCharExt_ptr) _do_this(::BULKIO::internal::dataCharExt::_PD_repoId);
      }
    };

    class dataDoubleExt :
      public virtual BULKIO::internal::_impl_dataDoubleExt,
      public virtual dataDouble,
        public virtual POA_ExtendedCF::NegotiableProvidesPort
    {
    public:
      virtual ~dataDoubleExt();

      inline ::BULKIO::internal::dataDoubleExt_ptr _this() {
        return (::BULKIO::internal::dataDoubleExt_ptr) _do_this(::BULKIO::internal::dataDoubleExt::_PD_repoId);
      }
    };

    class dataFloatExt :
      public virtual BULKIO::internal::_impl_dataFloatExt,
      public virtual dataFloat,
        public virtual POA_ExtendedCF::NegotiableProvidesPort
    {
    public:
      virtual ~dataFloatExt();

      inline ::BULKIO::internal::dataFloatExt_ptr _this() {
        return (::BULKIO::internal::dataFloatExt_ptr) _do_this(::BULKIO::internal::dataFloatExt::_PD_repoId);
      }
    };

    class dataLongExt :
      public virtual BULKIO::internal::_impl_dataLongExt,
      public virtual dataLong,
        public virtual POA_ExtendedCF::NegotiableProvidesPort
    {
    public:
      virtual ~dataLongExt();

      inline ::BULKIO::internal::dataLongExt_ptr _this() {
        return (::BULKIO::internal::dataLongExt_ptr) _do_this(::BULKIO::internal::dataLongExt::_PD_repoId);
      }
    };

    class dataLongLongExt :
      public virtual BULKIO::internal::_impl_dataLongLongExt,
      public virtual dataLongLong,
        public virtual POA_ExtendedCF::NegotiableProvidesPort
    {
    public:
      virtual ~dataLongLongExt();

      inline ::BULKIO::internal::dataLongLongExt_ptr _this() {
        return (::BULKIO::internal::dataLongLongExt_ptr) _do_this(::BULKIO::internal::dataLongLongExt::_PD_repoId);
      }
    };

    class dataOctetExt :
      public virtual BULKIO::internal::_impl_dataOctetExt,
      public virtual dataOctet,
        public virtual POA_ExtendedCF::NegotiableProvidesPort
    {
    public:
      virtual ~dataOctetExt();

      inline ::BULKIO::internal::dataOctetExt_ptr _this() {
        return (::BULKIO::internal::dataOctetExt_ptr) _do_this(::BULKIO::internal::dataOctetExt::_PD_repoId);
      }
    };

    class dataShortExt :
      public virtual BULKIO::internal::_impl_dataShortExt,
      public virtual dataShort,
        public virtual POA_ExtendedCF::NegotiableProvidesPort
    {
    public:
      virtual ~dataShortExt();

      inline ::BULKIO::internal::dataShortExt_ptr _this() {
        return (::BULKIO::internal::dataShortExt_ptr) _do_this(::BULKIO::internal::dataShortExt::_PD_repoId);
      }
    };

    class dataUlongExt :
      public virtual BULKIO::internal::_impl_dataUlongExt,
      public virtual dataUlong,
        public virtual POA_ExtendedCF::NegotiableProvidesPort
    {
    public:
      virtual ~dataUlongExt();

      inline ::BULKIO::internal::dataUlongExt_ptr _this() {
        return (::BULKIO::internal::dataUlongExt_ptr) _do_this(::BULKIO::internal::dataUlongExt::_PD_repoId);
      }
    };

    class dataUlongLongExt :
      public virtual BULKIO::internal::_impl_dataUlongLongExt,
      public virtual dataUlongLong,
        public virtual POA_ExtendedCF::NegotiableProvidesPort
    {
    public:
      virtual ~dataUlongLongExt();

      inline ::BULKIO::internal::dataUlongLongExt_ptr _this() {
        return (::BULKIO::internal::dataUlongLongExt_ptr) _do_this(::BULKIO::internal::dataUlongLongExt::_PD_repoId);
      }
    };

    class dataUshortExt :
      public virtual BULKIO::internal::_impl_dataUshortExt,
      public virtual dataUshort,
        public virtual POA_ExtendedCF::NegotiableProvidesPort
    {
    public:
      virtual ~dataUshortExt();

      inline ::BULKIO::internal::dataUshortExt_ptr _this() {
        return (::BULKIO::internal::dataUshortExt_ptr) _do_this(::BULKIO::internal::dataUshortExt::_PD_repoId);
      }
    };

    class dataBitExt :
      public virtual BULKIO::internal::_impl_dataBitExt,
      public virtual dataBit,
        public virtual POA_ExtendedCF::NegotiableProvidesPort
    {
    public:
      virtual ~dataBitExt();

      inline ::BULKIO::internal::dataBitExt_ptr _this() {
        return (::BULKIO::internal::dataBitExt_ptr) _do_this(::BULKIO::internal::dataBitExt::_PD_repoId);
      }
    };

    class dataXMLExt :
      public virtual BULKIO::internal::_impl_dataXMLExt,
      public virtual dataXML,
        public virtual POA_ExtendedCF::NegotiableProvidesPort
    {
    public:
      virtual ~dataXMLExt();

      inline ::BULKIO::internal::dataXMLExt_ptr _this() {
        return (::BULKIO::internal::dataXMLExt_ptr) _do_this(::BULKIO::internal::dataXMLExt::_PD_repoId);
      }
    };

    class dataFileExt :
      public virtual BULKIO::internal::_impl_dataFileExt,
      public virtual dataFile,
        public virtual POA_ExtendedCF::NegotiableProvidesPort
    {
    public:
      virtual ~dataFileExt();

      inline ::BULKIO::internal::dataFileExt_ptr _this() {
        return (::BULKIO::internal::dataFileExt_ptr) _do_this(::BULKIO::internal::dataFileExt::_PD_repoId);
      }
    };

  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE OBV_BULKIO
_CORBA_MODULE_BEG

  _CORBA_MODULE internal
  _CORBA_MODULE_BEG

  _CORBA_MODULE_END

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, BULKIO::internal::UsesPortStatisticsProviderExt_ptr _s);
void operator<<=(::CORBA::Any& _a, BULKIO::internal::UsesPortStatisticsProviderExt_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, BULKIO::internal::UsesPortStatisticsProviderExt_ptr& _s);

void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataCharExt_ptr _s);
void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataCharExt_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, BULKIO::internal::dataCharExt_ptr& _s);

void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataDoubleExt_ptr _s);
void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataDoubleExt_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, BULKIO::internal::dataDoubleExt_ptr& _s);

void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataFloatExt_ptr _s);
void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataFloatExt_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, BULKIO::internal::dataFloatExt_ptr& _s);

void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataLongExt_ptr _s);
void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataLongExt_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, BULKIO::internal::dataLongExt_ptr& _s);

void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataLongLongExt_ptr _s);
void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataLongLongExt_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, BULKIO::internal::dataLongLongExt_ptr& _s);

void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataOctetExt_ptr _s);
void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataOctetExt_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, BULKIO::internal::dataOctetExt_ptr& _s);

void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataShortExt_ptr _s);
void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataShortExt_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, BULKIO::internal::dataShortExt_ptr& _s);

void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataUlongExt_ptr _s);
void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataUlongExt_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, BULKIO::internal::dataUlongExt_ptr& _s);

void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataUlongLongExt_ptr _s);
void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataUlongLongExt_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, BULKIO::internal::dataUlongLongExt_ptr& _s);

void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataUshortExt_ptr _s);
void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataUshortExt_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, BULKIO::internal::dataUshortExt_ptr& _s);

void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataBitExt_ptr _s);
void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataBitExt_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, BULKIO::internal::dataBitExt_ptr& _s);

void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataXMLExt_ptr _s);
void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataXMLExt_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, BULKIO::internal::dataXMLExt_ptr& _s);

void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataFileExt_ptr _s);
void operator<<=(::CORBA::Any& _a, BULKIO::internal::dataFileExt_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, BULKIO::internal::dataFileExt_ptr& _s);



inline void
BULKIO::internal::UsesPortStatisticsProviderExt::_marshalObjRef(::BULKIO::internal::UsesPortStatisticsProviderExt_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
BULKIO::internal::dataCharExt::_marshalObjRef(::BULKIO::internal::dataCharExt_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
BULKIO::internal::dataDoubleExt::_marshalObjRef(::BULKIO::internal::dataDoubleExt_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
BULKIO::internal::dataFloatExt::_marshalObjRef(::BULKIO::internal::dataFloatExt_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
BULKIO::internal::dataLongExt::_marshalObjRef(::BULKIO::internal::dataLongExt_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
BULKIO::internal::dataLongLongExt::_marshalObjRef(::BULKIO::internal::dataLongLongExt_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
BULKIO::internal::dataOctetExt::_marshalObjRef(::BULKIO::internal::dataOctetExt_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
BULKIO::internal::dataShortExt::_marshalObjRef(::BULKIO::internal::dataShortExt_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
BULKIO::internal::dataUlongExt::_marshalObjRef(::BULKIO::internal::dataUlongExt_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
BULKIO::internal::dataUlongLongExt::_marshalObjRef(::BULKIO::internal::dataUlongLongExt_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
BULKIO::internal::dataUshortExt::_marshalObjRef(::BULKIO::internal::dataUshortExt_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
BULKIO::internal::dataBitExt::_marshalObjRef(::BULKIO::internal::dataBitExt_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
BULKIO::internal::dataXMLExt::_marshalObjRef(::BULKIO::internal::dataXMLExt_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
BULKIO::internal::dataFileExt::_marshalObjRef(::BULKIO::internal::dataFileExt_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_bio__dataExt
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_bio__dataExt
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_bio__dataExt
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_bio__dataExt
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_bio__dataExt
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_bio__dataExt
#endif

#endif  // __bio__dataExt_hh__

