// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __WellKnownProperties_hh__
#define __WellKnownProperties_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_WellKnownProperties
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_WellKnownProperties
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_WellKnownProperties
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE ExtendedCF

_CORBA_MODULE_BEG

  _CORBA_MODULE WKP

  _CORBA_MODULE_BEG

    _CORBA_MODULE_VAR _core_attr const char * DEVICEKIND;

    _CORBA_MODULE_VAR _core_attr const char * DEVICEMODEL;

    _CORBA_MODULE_VAR _core_attr const char * OS_NAME;

    _CORBA_MODULE_VAR _core_attr const char * OS_VERSION;

    _CORBA_MODULE_VAR _core_attr const char * PROCESSOR_NAME;

    _CORBA_MODULE_VAR _core_attr const char * AWARE_APPLICATION;

    _CORBA_MODULE_VAR _core_attr const char * STOP_TIMEOUT;

  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE POA_ExtendedCF
_CORBA_MODULE_BEG

  _CORBA_MODULE WKP
  _CORBA_MODULE_BEG

  _CORBA_MODULE_END

_CORBA_MODULE_END



_CORBA_MODULE OBV_ExtendedCF
_CORBA_MODULE_BEG

  _CORBA_MODULE WKP
  _CORBA_MODULE_BEG

  _CORBA_MODULE_END

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_WellKnownProperties
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_WellKnownProperties
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_WellKnownProperties
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_WellKnownProperties
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_WellKnownProperties
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_WellKnownProperties
#endif

#endif  // __WellKnownProperties_hh__

